export const CREATE_PAYMENT_METHOD = 'CREATE_PAYMENT_METHOD'
export const CREATE_PAYMENT_METHOD_PENDING = 'CREATE_PAYMENT_METHOD_PENDING'
export const CREATE_PAYMENT_METHOD_REJECTED = 'CREATE_PAYMENT_METHOD_REJECTED'
export const CREATE_PAYMENT_METHOD_FULFILLED = 'CREATE_PAYMENT_METHOD_FULFILLED'

export const SUBMIT_PAYMENT = 'SUBMIT_PAYMENT'
export const SUBMIT_PAYMENT_PENDING = 'SUBMIT_PAYMENT_PENDING'
export const SUBMIT_PAYMENT_REJECTED = 'SUBMIT_PAYMENT_REJECTED'
export const SUBMIT_PAYMENT_FULFILLED = 'SUBMIT_PAYMENT_FULFILLED'

export const CONFIRM_CARD_PAYMENT = 'CONFIRM_CARD_PAYMENT'
export const CONFIRM_CARD_PAYMENT_PENDING = 'CONFIRM_CARD_PAYMENT_PENDING'
export const CONFIRM_CARD_PAYMENT_FULFILLED = 'CONFIRM_CARD_PAYMENT_FULFILLED'
export const CONFIRM_CARD_PAYMENT_REJECTED = 'CONFIRM_CARD_PAYMENT_REJECTED'

export const GET_PLANS = 'GET_PLANS'
export const GET_PLANS_PENDING = 'GET_PLANS_PENDING'
export const GET_PLANS_FULFILLED = 'GET_PLANS_FULFILLED'
export const GET_PLANS_REJECTED = 'GET_PLANS_REJECTED'

export const RESET_PAYMENT_REDUCER = 'RESET_PAYMENT_REDUCER'
